name: My First Workflow

on: push

jobs:
    firs_job:
      runs-on: ubuntu-latest
      steps:
      - name: Welcome message
        run: echo "My firs GitHub Actions job"
          
      - name: List file
        run: ls

      - name: Read File
        run: cat ../README.md